oneup_flysystem:
    adapters:
        public_uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(S3_BUCKET)%'

    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            alias: League\Flysystem\Filesystem
