# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    SOAP_USERNAME: '%env(SOAP_USERNAME)%'
    SOAP_PASSWORD: '%env(SOAP_PASSWORD)%'
    SOAP_OASIS_BASE_URI: '%env(SOAP_OASIS_BASE_URI)%'
    SOAP_WSDL_URL: '%env(SOAP_WSDL_URL)%'
    SOAP_REQUEST_URL: '%env(SOAP_REQUEST_URL)%'
    ZAMTEL_BASE_URL: '%env(ZAMTEL_BASE_URL)%'
    ZAMTEL_THIRD_PARTY_ID: '%env(ZAMTEL_THIRD_PARTY_ID)%'
    ZAMTEL_PASSWORD: '%env(ZAMTEL_PASSWORD)%'
    ZAMTEL_SHORTCODE: '%env(ZAMTEL_SHORTCODE)%'
    MTN_BASE_URL: '%env(MTN_BASE_URL)%'
    MTN_USER_ID: '%env(MTN_USER_ID)%'
    MTN_API_KEY: '%env(MTN_API_KEY)%'
    MTN_COLLECTIONS_KEY: '%env(MTN_COLLECTIONS_KEY)%'
    MTN_TARGET_ENVIRONMENT: '%env(MTN_TARGET_ENVIRONMENT)%'
    PRODUCT_IMAGE_DIRECTORY: 'https://s3.amazonaws.com/%env(S3_BUCKET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Client\SoapClientInterface: '@App\Client\SoapClient'

    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: '%env(S3_BUCKET_REGION)%'
              credentials:
                  key: '%env(S3_ACCESS_KEY)%'
                  secret: '%env(S3_ACCESS_SECRET)%'